travis:
  secure:
    BINSTAR_TOKEN: TXpx6tXIv04gqvezD+ev9zRXPvD5gywJcggBPrOu+sLjTw+D9JeDvJWEx4Y2Ws4Sca2wCeCHWZ8V/HoMcwJOyzJwfSCC4K3qqZhIsTc6vMNkvwaDCAMtI1cOUf76XfwS1oMB62Q5D4rqS55LY/5U5rmQ3bVBr5b7aRjFSL/3G/wPxZnDmDbqq29g9uPS1Y86SKZJiTilF3hj4uaR6wb2HH8uuXN4oRRwCXh3PH1xtVX9nc4VsWDjd4jVvtkn6WVme3goIubBfOOI/wjAbkRCxKJY0xTeJKjzGg5uOZSHGtCStme7hGUdPFZXkjJonci1RT7Z+59TbT1y4DixyQwuoCvzs/Ebjj9bhmBUlDXjajrbYSpNILxg2R1mutpcBG+RU7Ukq1APYxsk7kPLt0IjbWdV8yQTpQE+OlNCPOfeyj21iqHJ3usIX7+3PBVVqd/bJMHIZ/k/ap9iaeuznFz8Az1N7tj3TDGgdcEwQ47NodiYZpHA2CXI8KwzOHJzuxDsimfrrkYzB1nh/u9T75Nfu+XaMH0lcyjMkn51vwqx/bqeLFeU9I4VkUB2b/XjKIVYLg40fvOIy83bbrOb6WbNsHRpaWA06W27kOfG1NHyq/NMha1qHp5LlRpFBoiixcVaKqo+zKx9fq6X72KKKwMPpEwd5LVqzz8v0cA1/C1Q958=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
